[env:esp32dev]
platform = espressif32@^6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient@^2.8
    madhephaestus/ESP32Servo
    https://github.com/beegee-tokyo/DHTesp.git
    https://github.com/tanakamasayuki/Arduino_TensorFlowLite_ESP32.git
